version: '3.1'

services:
  frontend:
    image: movie-go-frontend:4
    restart: always
    command: npm start
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - app-network
  backend: 
    image: movie-go-backend:10
    restart: always
    ports: 
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_DB: movies
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - /home/wrightchin/docker-volume/movie-go:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - app-network
networks: 
  app-network:
    driver: bridge
