apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: cityu-demo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/movie-listing-app-app-network: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - args:
            - npm
            - start
          image: wrightchin/movie-frontend-17
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
      serviceAccount: postgresdb
      restartPolicy: Always
status: {}
